name: semanaacademica2024
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.8
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  assets:
    - ./lib/assets/background_top.png
    - ./lib/assets/Estrelas.png
    - ./lib/assets/Foguete.png
    - ./lib/assets/competicao.png
    - ./lib/assets/palestrantes/alexandro.jpg
    - ./lib/assets/palestrantes/thiago.jpg
    - ./lib/assets/palestrantes/confira_mobile.png
    - ./lib/assets/palestrantes/confira_desktop.png
    - ./lib/assets/patrocinadores/patrocinadores.png
    - ./lib/assets/patrocinadores/aiqfome.png
    - ./lib/assets/patrocinadores/viasoft.jpg
    - ./lib/assets/patrocinadores/softfocus.png
    - ./lib/assets/patrocinadores/ids.jpg
    - ./lib/assets/realizacao/realizacao.png
    - ./lib/assets/realizacao/unimater.png
    - ./lib/assets/realizacao/sistemas.png
    - ./lib/assets/patrocinadores/sinnc.jpg
    - ./lib/assets/patrocinadores/bv.png 
    - ./lib/assets/logo.png
    - ./lib/assets/semana_academica.png
    - ./lib/assets/matergame.png
     
  fonts:
    - family: PressStart2P
      fonts:
        - asset: ./lib/fonts/PressStart2P-Regular.ttf
    - family: Jura
      fonts:
        - asset: ./lib/fonts/Jura-VariableFont_wght.ttf
    - family: Cristik
      fonts:
        - asset: ./lib/fonts/Cristik.ttf
        